version: '3'
services:
  db:
    container_name: "monorepo-db"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_PASSWORD:
      MYSQL_DATABASE: smilex-development
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: 'db'
    ports:
      - "3306:3306"
  web:
    container_name: "monorepo-server"
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    tty: true
    stdin_open: true
    environment:
      - "RAILS_ENV=development"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
